export { default as Home } from './Home'
export { default as Asistencia } from './Asistencia'
export { default as CreacionClases } from './CreacionClases'
export { default as DatosUsuario } from './DatosUsuario'
export { default as Historial } from './Historial'
export { default as Reportes } from './Reportes'
export { default as InformePreguntas } from './InformePreguntas/InformePreguntas'
export { default as CrearPreguntas } from './GestionClases'
